// types.js

export const FETCH_ROCKETS = 'FETCH_ROCKETS';
export const FETCH_ROCKETS_SUCCESS = 'FETCH_ROCKETS_SUCCESS';
export const FETCH_SELECTED_ROCKETS = 'FETCH_SELECTED_ROCKETS';
export const RESERVE_ROCKET = 'RESERVE_ROCKET';
export const CANCEL_RESERVATION = 'CANCEL_RESERVATION';
